openapi: 3.0.0
info:
  title: Chat App API
  description: API documentation for the Chat App
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'

paths:
  /conversation:
    post:
      summary: Create a new conversation
      description: Creates a new conversation for users.
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Conversation created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /conversation/add-member:
    post:
      summary: Add a member to a conversation
      description: Adds a user to an existing conversation.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Member added successfully
        '400':
          description: Invalid conversation ID or user ID
        '401':
          description: Unauthorized

  /conversation/{conversationId}/messages:
    get:
      summary: Get messages of a conversation
      description: Retrieve all messages from a specific conversation.
      parameters:
        - in: path
          name: conversationId
          required: true
          description: The ID of the conversation
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Messages retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found

  /friendship/request:
    post:
      summary: Send a friend request
      description: Sends a friend request to a user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Friend request sent
        '401':
          description: Unauthorized

  /friendship/respond/{id}:
    put:
      summary: Respond to a friend request
      description: Accept or reject a friend request.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the friend request
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Friend request responded successfully
        '400':
          description: Invalid request ID or input
        '401':
          description: Unauthorized

  /message/send:
    post:
      summary: Send a message
      description: Sends a message to a conversation.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Message sent successfully
        '400':
          description: Invalid message input
        '401':
          description: Unauthorized

  /message/{id}:
    get:
      summary: Get messages
      description: Retrieve messages by message ID.
      parameters:
        - in: path
          name: id
          required: true
          description: The ID of the message thread
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Messages retrieved successfully
        '401':
          description: Unauthorized
        '404':
          description: Messages not found

  /message/uploadFile:
    post:
      summary: Upload a file
      description: Uploads a file to the server.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: File uploaded successfully
        '400':
          description: Invalid file input
        '401':
          description: Unauthorized

  /message/downloadFile/{filename}:
    get:
      summary: Download a file
      description: Downloads a file from the server.
      parameters:
        - in: path
          name: filename
          required: true
          description: The name of the file to download
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: File downloaded successfully
        '404':
          description: File not found
        '401':
          description: Unauthorized

  /notification:
    get:
      summary: Get notifications
      description: Retrieves all notifications for the logged-in user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Notifications retrieved successfully
        '401':
          description: Unauthorized

  /notification/{notificationId}/read:
    patch:
      summary: Mark a notification as read
      description: Marks a specific notification as read.
      parameters:
        - in: path
          name: notificationId
          required: true
          description: The ID of the notification to mark as read
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Notification marked as read successfully
        '404':
          description: Notification not found
        '401':
          description: Unauthorized

  /search/messages:
    get:
      summary: Search messages
      description: Search messages across all conversations.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Search results retrieved successfully
        '400':
          description: Invalid search input
        '401':
          description: Unauthorized

  /register:
    post:
      summary: Register a new user
      description: Registers a new user to the system.
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /login:
    post:
      summary: Login a user
      description: Authenticates and logs in a user.
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credentials

  /me:
    get:
      summary: Get the profile of the current user
      description: Retrieves the profile information of the currently logged-in user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
        '401':
          description: Unauthorized

  /me:
    put:
      summary: Update the profile of the current user
      description: Updates the profile information of the currently logged-in user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile updated successfully
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
